//! Autogenerated weights for pallet_ghonity
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-11-18, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Ghost-Protocol-Node`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_ghonity.
pub trait WeightInfo {
	fn follow() -> Weight;
	fn unfollow() -> Weight;
	fn update_reputation() -> Weight;
}

/// Weights for pallet_ghonity using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Ghonity Follows (r:1 w:1)
	/// Proof: Ghonity Follows (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: Ghonity FollowingCount (r:1 w:1)
	/// Proof: Ghonity FollowingCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Ghonity FollowerCount (r:0 w:1)
	/// Proof: Ghonity FollowerCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	fn follow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `5054`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 5054)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}

	/// Storage: Ghonity Follows (r:1 w:1)
	/// Proof: Ghonity Follows (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: Ghonity FollowingCount (r:0 w:1)
	/// Proof: Ghonity FollowingCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Ghonity FollowerCount (r:0 w:1)
	/// Proof: Ghonity FollowerCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	fn unfollow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `2543`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 2543)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}

	/// Storage: Ghonity ReputationScores (r:1 w:1)
	/// Proof: Ghonity ReputationScores (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	fn update_reputation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `2511`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 2511)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Ghonity Follows (r:1 w:1)
	/// Proof: Ghonity Follows (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: Ghonity FollowingCount (r:1 w:1)
	/// Proof: Ghonity FollowingCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Ghonity FollowerCount (r:0 w:1)
	/// Proof: Ghonity FollowerCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	fn follow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `5054`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 5054)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}

	/// Storage: Ghonity Follows (r:1 w:1)
	/// Proof: Ghonity Follows (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: Ghonity FollowingCount (r:0 w:1)
	/// Proof: Ghonity FollowingCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: Ghonity FollowerCount (r:0 w:1)
	/// Proof: Ghonity FollowerCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	fn unfollow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108`
		//  Estimated: `2543`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 2543)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}

	/// Storage: Ghonity ReputationScores (r:1 w:1)
	/// Proof: Ghonity ReputationScores (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	fn update_reputation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `2511`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(11_000_000, 2511)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
