//! Autogenerated weights for pallet_chainghost
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI
//! DATE: 2025-11-18
//! HOSTNAME: Ghost Protocol Development Node
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_chainghost.
pub trait WeightInfo {
	fn execute_intent() -> Weight;
	fn record_journey() -> Weight;
	fn update_intent_status() -> Weight;
}

/// Weights for pallet_chainghost using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: ChainGhost NextIntentId (r:1 w:1)
	/// Storage: ChainGhost IntentById (r:0 w:1)
	/// Storage: ChainGhost IntentsByAccount (r:1 w:1)
	fn execute_intent() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}

	/// Storage: ChainGhost IntentById (r:1 w:0)
	/// Storage: ChainGhost JourneyByIntent (r:1 w:1)
	fn record_journey() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}

	/// Storage: ChainGhost IntentById (r:1 w:1)
	fn update_intent_status() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: ChainGhost NextIntentId (r:1 w:1)
	/// Storage: ChainGhost IntentById (r:0 w:1)
	/// Storage: ChainGhost IntentsByAccount (r:1 w:1)
	fn execute_intent() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}

	/// Storage: ChainGhost IntentById (r:1 w:0)
	/// Storage: ChainGhost JourneyByIntent (r:1 w:1)
	fn record_journey() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}

	/// Storage: ChainGhost IntentById (r:1 w:1)
	fn update_intent_status() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
