
//! Autogenerated weights for pallet_g3mail
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-11-18, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ghost-node`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/ghost-node
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_g3mail
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// pallets/g3mail/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_g3mail.
pub trait WeightInfo {
	fn register_public_key() -> Weight;
	fn send_message() -> Weight;
	fn mark_message_read() -> Weight;
}

/// Weights for pallet_g3mail using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: G3Mail PublicKeys (r:1 w:1)
	/// Proof: G3Mail PublicKeys (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	fn register_public_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3625`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3625)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: G3Mail PublicKeys (r:1 w:0)
	/// Proof: G3Mail PublicKeys (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: G3Mail InboxCount (r:1 w:1)
	/// Proof: G3Mail InboxCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: G3Mail NextMessageId (r:1 w:1)
	/// Proof: G3Mail NextMessageId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: G3Mail MessagesByRecipient (r:0 w:1)
	/// Proof: G3Mail MessagesByRecipient (max_values: None, max_size: Some(300), added: 2775, mode: MaxEncodedLen)
	fn send_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `100`
		//  Estimated: `3625`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 3625)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: G3Mail MessagesByRecipient (r:1 w:1)
	/// Proof: G3Mail MessagesByRecipient (max_values: None, max_size: Some(300), added: 2775, mode: MaxEncodedLen)
	fn mark_message_read() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `3765`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 3765)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: G3Mail PublicKeys (r:1 w:1)
	/// Proof: G3Mail PublicKeys (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	fn register_public_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3625`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 3625)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: G3Mail PublicKeys (r:1 w:0)
	/// Proof: G3Mail PublicKeys (max_values: None, max_size: Some(160), added: 2635, mode: MaxEncodedLen)
	/// Storage: G3Mail InboxCount (r:1 w:1)
	/// Proof: G3Mail InboxCount (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
	/// Storage: G3Mail NextMessageId (r:1 w:1)
	/// Proof: G3Mail NextMessageId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: G3Mail MessagesByRecipient (r:0 w:1)
	/// Proof: G3Mail MessagesByRecipient (max_values: None, max_size: Some(300), added: 2775, mode: MaxEncodedLen)
	fn send_message() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `100`
		//  Estimated: `3625`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 3625)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: G3Mail MessagesByRecipient (r:1 w:1)
	/// Proof: G3Mail MessagesByRecipient (max_values: None, max_size: Some(300), added: 2775, mode: MaxEncodedLen)
	fn mark_message_read() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `3765`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 3765)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
